services:
  web:
    container_name: "nginx"
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ../app/public:/var/www/html
      - ../app/src/index.php:/var/www/html/index.php
    depends_on:
      - phpfpm
    networks:
      - my_network

  phpfpm:
    container_name: "phpfpm"
    build:
      context: .
      dockerfile: php-dockerfile
    image: php:8.2-fpm
    volumes:
      - ../app/src:/var/www/html
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=256M
    depends_on:
      - mysqldb
    networks:
      - my_network

  mysqldb:
    container_name: "mysqldb"
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Gr0t!
      MYSQL_DATABASE: blog
      MYSQL_USER: biky
      MYSQL_PASSWORD: begucool
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - ../db/data/:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
